### PR TITLE
Update T2SDE

### PR DESCRIPTION
**Pull request by N0T4G**

### CODE REVIEW

**Comment by FabioLolix** [comment]
Very well René, can you make some edits?

Please encapsulate URLs with <>, otherwise on the builded site they will not be links

For category add 'Source based'

For 'on LWN.net' and 'In the timeline' write yes, (as T2SDE is present on https://lwn.net/Distributions/ and the Linux distributions timeline) and add https://lwn.net/Articles/856447/ to the media coverage links

**Comment by N0T4G** [comment]
Hey @FabioLolix ,

Thanks for taking the time to review this so quickly!

Actually I'm not René but NoTag, another maintainer of T2. (René is [rxrbln](https://github.com/rxrbln/) on GitHub) :)

I will try to do the changes you mention in the few next hours!

**Comment by N0T4G** [comment]
@FabioLolix Done.
Let me know if I missed something or need to do more changes.

Cheers!

**Comment by FabioLolix** [comment]
@N0T4G you have deleted the user/password table/chart, what is the user/password situation on T2SDE?

**Comment by N0T4G** [comment]
@FabioLolix Ah right, the default user is root and the default password is specified by the user at install time.
Should I put it back?

**Comment by FabioLolix** [comment]
>  Should I put it back?

I'll take care of that, thanks for your effort!

**Comment by N0T4G** [comment]
Thank you! :D

**Pull request merged**
